//! IPC envelope types (REQ-ARCH-003.1, .2, .3).
//!
//! These are the wire shapes described in the design document's "IPC
//! Protocol" section. They derive `ts_rs::TS`, so the TypeScript interfaces
//! in `frontend/src/generated/` are produced from this Rust source of truth
//! rather than hand-maintained alongside it.

use helix_core::error::AppError;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// Default command timeout, per REQ-ARCH-003.3. Overridable per request via
/// [`IpcRequest::timeout_ms`], and per dispatcher via
/// [`crate::IpcDispatcher::with_default_timeout_ms`].
pub const DEFAULT_TIMEOUT_MS: u32 = 30_000;

/// A request sent from the frontend to the kernel over Tauri IPC.
///
/// `correlation_id` is generated by the caller and is the identity used for
/// both response matching and cancellation (REQ-ARCH-003.2). A
/// `timeout_ms` of `None` or `0` means "use the dispatcher default".
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../../frontend/src/generated/")]
pub struct IpcRequest<T> {
    pub command: String,
    pub correlation_id: String,
    pub payload: T,
    pub timeout_ms: Option<u32>,
}

impl<T> IpcRequest<T> {
    pub fn new(command: impl Into<String>, correlation_id: impl Into<String>, payload: T) -> Self {
        Self {
            command: command.into(),
            correlation_id: correlation_id.into(),
            payload,
            timeout_ms: None,
        }
    }

    pub fn with_timeout_ms(mut self, timeout_ms: u32) -> Self {
        self.timeout_ms = Some(timeout_ms);
        self
    }
}

/// A response sent from the kernel to the frontend over Tauri IPC.
///
/// Exactly one of `result` and `error` is populated. `correlation_id`
/// always echoes the originating request, so an orphan response (one whose
/// id the frontend is no longer waiting on) is discarded rather than
/// misattributed — design document Property 4.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../../frontend/src/generated/")]
pub struct IpcResponse<T> {
    pub correlation_id: String,
    pub result: Option<T>,
    pub error: Option<AppError>,
}

impl<T> IpcResponse<T> {
    pub fn ok(correlation_id: impl Into<String>, result: T) -> Self {
        Self {
            correlation_id: correlation_id.into(),
            result: Some(result),
            error: None,
        }
    }

    pub fn err(correlation_id: impl Into<String>, error: AppError) -> Self {
        Self {
            correlation_id: correlation_id.into(),
            result: None,
            error: Some(error),
        }
    }

    pub fn is_ok(&self) -> bool {
        self.error.is_none()
    }
}

/// Frontend request to abort an in-flight command by correlation ID
/// (REQ-ARCH-003.2).
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../../frontend/src/generated/")]
pub struct CancelRequest {
    pub correlation_id: String,
}

/// Result of a cancellation attempt. `cancelled` is false when the
/// correlation ID was not in flight, which is a normal race (the command
/// finished first), not an error.
#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../../frontend/src/generated/")]
pub struct CancelResponse {
    pub correlation_id: String,
    pub cancelled: bool,
}

#[cfg(test)]
mod tests {
    use super::*;
    use helix_core::error::ErrorCategory;

    #[test]
    fn request_round_trips_through_json() {
        let req = IpcRequest::new(
            "ipc.ping",
            "abc-123",
            serde_json::json!({ "message": "hi" }),
        )
        .with_timeout_ms(500);
        let json = serde_json::to_string(&req).unwrap();
        let back: IpcRequest<serde_json::Value> = serde_json::from_str(&json).unwrap();
        assert_eq!(back.command, "ipc.ping");
        assert_eq!(back.correlation_id, "abc-123");
        assert_eq!(back.timeout_ms, Some(500));
    }

    #[test]
    fn ok_response_carries_result_and_no_error() {
        let resp = IpcResponse::ok("abc-123", 7u32);
        assert!(resp.is_ok());
        assert_eq!(resp.result, Some(7));
        assert!(resp.error.is_none());
    }

    #[test]
    fn err_response_carries_error_and_no_result() {
        let resp: IpcResponse<u32> =
            IpcResponse::err("abc-123", AppError::timeout("took too long"));
        assert!(!resp.is_ok());
        assert!(resp.result.is_none());
        assert_eq!(resp.error.unwrap().category, ErrorCategory::Timeout);
    }

    #[test]
    fn default_timeout_is_thirty_seconds() {
        assert_eq!(DEFAULT_TIMEOUT_MS, 30_000);
    }
}
